In [3]:
import numpy as np

In [4]:
data=np.genfromtxt("heart.csv",delimiter=",",skip_header=True)

### Extracting relevent column Data

In [20]:
sex=data[:,1]
print(f"sex: {sex[:9]}")
target=data[:,13]
print(f"target: {target[:9]}")
chol=data[:,4]
print(f"chol: {chol[:9]}")
trestbps=data[:,3]
print(f"trestbps: {trestbps[:9]}")
age=data[:,0]
print(f"age: {age[:9]}")

sex: [1. 1. 0. 1. 0. 1. 0. 1. 1.]
target: [1. 1. 1. 1. 1. 1. 1. 1. 1.]
chol: [233. 250. 204. 236. 354. 192. 294. 263. 199.]
trestbps: [145. 130. 130. 120. 120. 140. 140. 120. 172.]
age: [63. 37. 41. 56. 57. 57. 56. 44. 52.]


In [21]:
#Age
print("----Basic Descriptive Statistics on Age----")
print(f"Mean, {round(np.mean(age))}")
print(f"Median, {np.median(age)}")
print(f"Standard Deviation, {round(np.std(age))}")
print(f"Minimum, {np.min(age)}")
print(f"Maximum, {np.max(age)}")

----Basic Descriptive Statistics on Age----
Mean, 54
Median, 55.0
Standard Deviation, 9
Minimum, 29.0
Maximum, 77.0


In [36]:
#Chol
print("----Basic Descriptive Statistics on Chol----")
print(f"Mean, {round(np.mean(chol))}")
print(f"Median, {np.median(chol)}")
print(f"Standard Deviation, {round(np.std(chol))}")
print(f"Minimum, {np.min(chol)}")
print(f"Maximum, {np.max(chol)}")

----Basic Descriptive Statistics on Chol----
Mean, 246
Median, 240.0
Standard Deviation, 52
Minimum, 126.0
Maximum, 564.0


In [37]:
#trestbps
print("----Basic Descriptive Statistics on trestbps----")
print(f"Mean, {round(np.mean(trestbps))}")
print(f"Median, {np.median(trestbps)}")
print(f"Standard Deviation, {round(np.std(trestbps))}")
print(f"Minimum, {np.min(trestbps)}")
print(f"Maximum, {np.max(trestbps)}")

----Basic Descriptive Statistics on trestbps----
Mean, 132
Median, 130.0
Standard Deviation, 18
Minimum, 94.0
Maximum, 200.0


### Data Filtering
* Target: 1 has heart disease and 0 does not

In [18]:
print(f"Number of rows before filtering: {len(data)}")

Number of rows before filtering: 303


How many people have heart disease

In [47]:
filtered_data=data[(target==1)]
print(f"Number of people with heart disease: {len(filtered_data)}")

Number of people with heart disease: 165


How many people over the average age of 54 have heart disease

In [46]:
filtered_data=data[(age>54) & (target==1)]
print(f"Number of people over 54 with heart disease: {len(filtered_data)}")

Number of people over 54 with heart disease: 65


### Men and women in study
* men = 0
* women = 1

number of women in data set

In [42]:
filtered_data=data[(sex==1)]
print(f"Number of women in data set: {len(filtered_data)}")

Number of women in data set: 207


How many women have heart disease

In [43]:
filtered_data=data[(sex==1) & (target==1)]
print(f"Number of women with heart disease: {len(filtered_data)}")

Number of women with heart disease: 93


number of men in data set

In [44]:
filtered_data=data[(sex==0)]
print(f"Number of men in data set: {len(filtered_data)}")

Number of men in data set: 96


How many men have heart disease

In [45]:
filtered_data=data[(sex==0) & (target==1)]
print(f"Number of men with heart disease: {len(filtered_data)}")

Number of men with heart disease: 72


### Chol in study

how many people with chol over 246 have heart disease

In [39]:
filtered_data=data[(chol>246) & (target==1)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 63


how many people with chol over 246 and over the age of 54 have heart disease

In [40]:
filtered_data=data[(chol>246) & (age>54) & (target==1)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 29


how many people with chol over 246 and over the age of 54

In [41]:
filtered_data=data[(chol>246) & (age>54)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 82


### trestbps in study

Number of people with blood pressure

In [52]:
filtered_data=data[(trestbps>132)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 124


How many people with a resting blood pressure over 132 have heart disease 

In [48]:
filtered_data=data[(trestbps>132) & (target==1)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 62


Number of people over the age of 54 and a higher blood pressure than 132

In [50]:
filtered_data=data[(trestbps>132) & (age>54)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 83


Number of people with a blood pressure over 132 and an age over 54 and heart disease

In [51]:
filtered_data=data[(trestbps>132) & (age>54) & (target==1)]
print(f"Number of rows after filtering: {len(filtered_data)}")

Number of rows after filtering: 33


### Correlation Analysis
* due to target being binary the correlation analysis is not accurate

In [54]:
corr_sex=np.corrcoef(target,sex,rowvar=False)
print(f"Corr target and sex {corr_sex}")

Corr target and sex [[ 1.         -0.28093658]
 [-0.28093658  1.        ]]


In [55]:
corr_chol=np.corrcoef(target,chol,rowvar=False)
print(f"Corr target and chol {corr_chol}")

Corr target and chol [[ 1.         -0.08523911]
 [-0.08523911  1.        ]]


In [56]:
corr_trestbps=np.corrcoef(target,trestbps,rowvar=False)
print(f"Corr target and trestbps {corr_trestbps}")

Corr target and trestbps [[ 1.         -0.14493113]
 [-0.14493113  1.        ]]
